// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANCFRADDt-kwPr0BVkA-jLnSFIlY42YxU',
    appId: '1:776047144296:web:a29d22c623bb3082857add',
    messagingSenderId: '776047144296',
    projectId: 'nchat-35011',
    authDomain: 'nchat-35011.firebaseapp.com',
    storageBucket: 'nchat-35011.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3V9xFid2hKNeD_YWCSBLFth1ZZ9FOURg',
    appId: '1:776047144296:android:c590eb4c1a5e1e07857add',
    messagingSenderId: '776047144296',
    projectId: 'nchat-35011',
    storageBucket: 'nchat-35011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeT2am8GVohLQ-4gPTkIXUUTtMGxHkRUM',
    appId: '1:776047144296:ios:d35fc8c274c6b319857add',
    messagingSenderId: '776047144296',
    projectId: 'nchat-35011',
    storageBucket: 'nchat-35011.appspot.com',
    iosClientId: '776047144296-9dnj87u7ne3o0qltrjkm6uc0u7ct50fm.apps.googleusercontent.com',
    iosBundleId: 'com.korayliman.app',
  );
}
